-- Fase 17: estado operacional e auditoria administrativa
-- Aplicar de forma versionada; rollback em 005_phase17_operations_rollback.sql.
create table if not exists public.iv_admin_audit (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_char_id uuid,
  target_char_id uuid,
  action text not null check (char_length(action) between 1 and 48),
  details jsonb not null default '{}'::jsonb
);
alter table public.iv_admin_audit enable row level security;
-- Sem policies para anon/authenticated: tabela fica inacessível pela API pública/RLS.
create index if not exists iv_admin_audit_created_at_idx on public.iv_admin_audit(created_at desc);
