'use strict';const test=require('node:test');const assert=require('node:assert/strict');const DungeonManager=require('../server/dungeons/dungeon-manager');const {DUNGEONS}=require('../server/data/dungeons');
function setup(now=1000){const sent=[],players=new Map();const a={id:'a',L:24,ws:{}},b={id:'b',L:25,ws:{}};const party={leader:'a',members:new Set(['a','b'])};a.party=b.party=party;players.set('a',a);players.set('b',b);const dm=new DungeonManager({catalog:DUNGEONS,players,send:(ws,m)=>sent.push(m),now:()=>now,idFactory:()=> 'inst-1'});return {dm,a,b,sent,players};}
test('catalogo define dungeon 20-30, normal/dificil e quatro estagios',()=>{const d=DUNGEONS.cripta_ecos;assert.equal(d.levelMin,20);assert.equal(d.levelMax,30);assert.deepEqual(Object.keys(d.difficulties),['normal','dificil']);assert.equal(d.stages.length,4);assert.ok(d.bosses.matriarca_ecos.mechanics.includes('soak'));});
test('entrada exige lider, party e nivel',()=>{const {dm,a,b}=setup();assert.equal(dm.validateEntry(b,'cripta_ecos').ok,false);assert.equal(dm.validateEntry(a,'cripta_ecos').ok,true);b.L=31;assert.equal(dm.validateEntry(a,'cripta_ecos').ok,false);});
test('instancias sao isoladas e participantes recebem entrada',()=>{const {dm,a,sent}=setup();const r=dm.create(a,'cripta_ecos');assert.equal(r.ok,true);assert.equal(r.instance.id,'inst-1');assert.equal(r.instance.participants.size,2);assert.equal(sent.filter(x=>x.t==='dungeonEnter').length,2);});
test('waves objetivo miniboss boss e chest individual',()=>{const {dm,a,b}=setup();const i=dm.create(a,'cripta_ecos').instance;dm.progress(a,'wave',null,2);assert.equal(i.stageIndex,1);dm.progress(a,'interact','selo_eco',3);assert.equal(i.stageIndex,2);dm.progress(a,'boss','vigia_runico');assert.equal(i.stageIndex,3);dm.progress(a,'boss','matriarca_ecos');assert.equal(i.state,'completed');assert.equal(dm.claimChest(a).ok,true);assert.equal(dm.claimChest(a).ok,false);assert.equal(dm.claimChest(b).ok,true);});
test('reconnect restaura instancia ativa',()=>{const {dm,a}=setup();dm.create(a,'cripta_ecos');dm.disconnect(a);assert.equal(dm.getForPlayer(a.id).connected.has(a.id),false);assert.ok(dm.reconnect(a));});
test('boss telegraph valida mecanica e analytics registra wipe/complete',()=>{const {dm,a}=setup();const i=dm.create(a,'cripta_ecos').instance;dm.progress(a,'wave',null,2);dm.progress(a,'interact','selo_eco',3);assert.ok(dm.bossMechanic(i.id,'cone',{x:2,z:3}));assert.equal(dm.bossMechanic(i.id,'soak'),null);dm.wipe(i.id);assert.equal(i.wipes,1);assert.ok(dm.analytics.some(e=>e.type==='mechanic'));});
test('dificil requer conclusao normal e lockout bloqueia nova entrada',()=>{const {dm,a}=setup();assert.equal(dm.validateEntry(a,'cripta_ecos','dificil').ok,false);const i=dm.create(a,'cripta_ecos').instance;dm.complete(i);dm.cleanup(i);assert.equal(dm.validateEntry(a,'cripta_ecos').ok,false);});
test('combate da instancia calcula dano no servidor e nao aceita alvo inventado',()=>{const {dm,a}=setup();a.stats={attack:5000};const i=dm.create(a,'cripta_ecos').instance;assert.equal(dm.attack(a,'fake').ok,false);for(const id of [...i.entities.keys()])dm.attack(a,id);assert.ok(i.wavesCleared>=1||i.stageIndex>0);});
test('assets Blender obrigatorios existem dentro do budget web',()=>{const fs=require('node:fs'),path=require('node:path');for(const n of ['room_module.glb','gate_echo.glb','echo_seal.glb','loot_chest.glb','miniboss_vigia_runico.glb','boss_matriarca_ecos.glb']){const s=fs.statSync(path.join(__dirname,'..','public','assets','dungeons','cripta_ecos',n)).size;assert.ok(s>1000&&s<256000,n+': '+s);}});
