'use strict';const test=require('node:test'),assert=require('node:assert/strict'),PvpManager=require('../server/pvp/pvp-manager');const {ARENAS,TERRITORIES}=require('../server/data/pvp');
function mk(id,name,L=60,guild=null){return{id,name,L,x:0,z:0,hp:500,maxHp:500,dead:false,ws:{readyState:1},stats:{atkMax:120,defense:40,maxHp:500},dados:{pvp:{}},guild,dirty:false}}
function setup(){let now=1000;const sent=[],players=new Map(),a=mk(1,'Ares'),b=mk(2,'Bela');players.set(1,a);players.set(2,b);const m=new PvpManager({players,send:(ws,msg)=>sent.push(msg),now:()=>now});m.onLogin(a);m.onLogin(b);return{m,a,b,sent,setNow:x=>now=x}}
test('fase 14 possui arenas e tres objetivos territoriais',()=>{assert.ok(ARENAS.campo_honra);assert.equal(Object.keys(TERRITORIES).length,3)});
test('pvp aberto e fogo amigo sao bloqueados',()=>{const{x:m,a,b}= {x:setup().m,...setup()};assert.equal(m.canAttack(a,b),false)});
test('duelo exige convite, aceite e proximidade',()=>{const{m,a,b}=setup();assert.equal(m.invite(a,'Bela'),true);assert.equal(m.canAttack(a,b),false);assert.equal(m.accept(b,'Ares'),true);assert.equal(m.canAttack(a,b),true)});
test('morte em duelo registra honra, vitoria e derrota persistentes',()=>{const{m,a,b}=setup();m.invite(a,'Bela');m.accept(b,'Ares');b.hp=1;assert.equal(m.attack(a,'Bela'),true);assert.equal(a.dados.pvp.duelWins,1);assert.equal(b.dados.pvp.duelLosses,1);assert.ok(a.dados.pvp.honor>0);assert.equal(b.dead,true)});
test('arena pareia dois jogadores e autoriza combate',()=>{const{m,a,b}=setup();assert.equal(m.queueArena(a),true);assert.equal(m.queueArena(b),true);assert.equal(a.pvpArena,'campo_honra');assert.equal(b.pvpArena,'campo_honra');assert.equal(m.canAttack(a,b),true)});
test('guerra de guildas requer lideres e soma placar',()=>{const{m,a,b}=setup();a.guild={id:'g1',nome:'Solar',cargo:'lider',nivel:10};b.guild={id:'g2',nome:'Lunar',cargo:'lider',nivel:10};assert.equal(m.declare(a,'Bela'),true);assert.equal(m.acceptWar(b,'Solar'),true);assert.equal(m.canAttack(a,b),true);b.hp=1;m.attack(a,'Bela');const w=[...m.wars.values()][0];assert.equal(w.score.g1,1);assert.equal(a.dados.pvp.guildKills,1)});
test('territorio exige guilda, nivel e presenca fisica',()=>{const{m,a}=setup();a.guild={id:'g1',nome:'Solar',cargo:'lider',nivel:10};const t=TERRITORIES.fortaleza_norte;a.x=t.x;a.z=t.z;assert.equal(m.capture(a,t.id),true);assert.equal(m.territories.get(t.id).guildId,'g1')});
test('ranking ordena por honra sem confiar no cliente',()=>{const{m,a,b}=setup();a.dados.pvp.honor=10;b.dados.pvp.honor=50;assert.equal(m.ranking()[0].name,'Bela')});
test('cliente possui aba PvP, arena, guerra e territorios',()=>{const fs=require('node:fs'),h=fs.readFileSync(require('node:path').join(__dirname,'..','public','index.html'),'utf8');for(const s of ["data-stab=\"pvp\"",'arenaQueue','warDeclare','data-capture','Ranking de Honra'])assert.ok(h.includes(s),s)});
test('server integra manager, persistencia e websocket PvP',()=>{const fs=require('node:fs'),s=fs.readFileSync(require('node:path').join(__dirname,'..','server.js'),'utf8');for(const x of ['PvpManager','pvpManager.onLogin','pvpManager.onDisconnect',"case 'pvp'","'pvp'"])assert.ok(s.includes(x),x)});
