'use strict';const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const PetManager=require('../server/pets/pet-manager'),SocialManager=require('../server/social/social-manager'),{PETS}=require('../server/data/pets');
const send=()=>{},itemManager={addItem(p,it){p.dados.inv=p.dados.inv||[];if(p.dados.inv.length>=32)return false;p.dados.inv.push({...it});return true;},sync(){}};
test('catalogo tem 3 pets e 3 tiers modestos',()=>{assert.equal(Object.keys(PETS).length,3);for(const p of Object.values(PETS)){assert.equal(p.tiers.length,3);assert.ok(p.pickupRadius<=6);}});
test('pet persiste summon, rename e evolucao',()=>{const p={dados:{},ws:{}};const pm=new PetManager({send,itemManager});assert.ok(pm.grant(p,'lumim'));assert.ok(pm.summon(p,'lumim'));assert.ok(pm.rename(p,'lumim','Luz'));pm.gainExp(p,20000);assert.equal(p.dados.petActive,'lumim');assert.equal(p.dados.pets.lumim.nickname,'Luz');assert.equal(p.dados.pets.lumim.tier,3);});
test('pickup pet respeita raio server-side',()=>{const p={x:0,z:0,dados:{pets:{lumim:{id:'lumim',level:1,exp:0,tier:1}},petActive:'lumim'},ws:{}};const pm=new PetManager({send,itemManager});assert.equal(pm.pickup(p,{x:5,z:0}).ok,true);assert.equal(pm.pickup(p,{x:7,z:0}).ok,false);});
function social(){const players=new Map(),messages=[];const sm=new SocialManager({players,send:(w,m)=>messages.push(m),itemManager});const a={id:1,name:'Ana',L:20,ws:{},dados:{gold:100,inv:[{id:'pocao',n:2}]},dirty:false},b={id:2,name:'Beto',L:21,ws:{},dados:{gold:0,inv:[]},dirty:false};players.set(1,a);players.set(2,b);return {sm,a,b,messages};}
test('friends, blacklist e whisper respeitam bloqueio',()=>{const {sm,a,b,messages}=social();assert.ok(sm.addFriend(a,'Beto'));assert.ok(sm.whisper(a,'Beto','oi'));assert.ok(messages.some(x=>x.t==='whisper'));sm.block(b,'Ana');assert.equal(sm.whisper(a,'Beto','bloqueado'),false);});
test('mail transfere ouro/item uma vez e claim e seguro',()=>{const {sm,a,b}=social();const r=sm.sendMail(a,'Beto','Presente','teste',[{id:'pocao',n:1}],40);assert.ok(r.ok);assert.equal(a.dados.gold,60);assert.equal(b.dados.mail.length,1);assert.ok(sm.claimMail(b,r.id).ok);assert.equal(b.dados.gold,40);assert.equal(sm.claimMail(b,r.id).ok,false);});
test('assets Blender dos 9 tiers existem e cabem no budget',()=>{for(const id of Object.keys(PETS))for(let t=1;t<=3;t++){const f=path.join(__dirname,'..','public','assets','pets',id+'_t'+t+'.glb'),s=fs.statSync(f).size;assert.ok(s>1000&&s<256000,id+t+':'+s);}});
test('save legado do cliente nao pode adulterar pets/social/mail',()=>{const server=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');for(const k of ["'pets'","'petActive'","'social'","'mail'"])assert.ok(server.includes(k),k);});
test('cliente possui UI mobile social/pets e servidor integra reconnect',()=>{const html=fs.readFileSync(path.join(__dirname,'..','public','index.html'),'utf8'),server=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');for(const x of ['winPets','Amigos','Correio','Bloqueados','inviteByName','socialState','petState'])assert.ok(html.includes(x),x);for(const x of ['PetManager','SocialManager','preservarGrupo','restaurarGrupo','petPickup'])assert.ok(server.includes(x),x);});
