'use strict';

const EQUIPMENT=require('../data/equipment');
const QUESTS=require('../data/quests');
const CONSUMABLES={pocao_vida:{price:20},pocao_mana:{price:20},pocao_energia:{price:20},combustivel:{price:60},pedra_aprimorar:{price:150},runa_menor:{price:300},runa_maior:{price:1500},perg_protecao:{price:2500},perg_sorte:{price:1200}};
const MATERIAL_VALUES={gosma:3,pelo:5,chapeu:8,presa:12,musgo:18,pele_lobo:24,seda:30,essencia:38,nucleo:48};
const UP_CHANCE=[1,1,1,.9,.75,.6,.45,.35,.25,.15,.1];
const priceOf=id=>CONSUMABLES[id]?.price||EQUIPMENT[id]&&Math.round(30*Math.pow(EQUIPMENT[id].req,1.5)+60);
const remove=(inv,id,n)=>{const row=inv.find(x=>x&&x.id===id&&x.up===undefined);if(!row||row.n<n)return false;row.n-=n;if(row.n<=0)inv.splice(inv.indexOf(row),1);return true;};
const count=(inv,id)=>inv.filter(x=>x&&x.id===id).reduce((n,x)=>n+x.n,0);
const reservedQuestItems=player=>{const ids=new Set(),active=player.dados&&player.dados.quests&&player.dados.quests.active||{};for(const id of Object.keys(active)){const q=QUESTS[id];if(!q)continue;for(const o of (q.objectives||[]))if((o.type==='collect'||o.type==='delivery')&&o.itemId)ids.add(o.itemId);}return ids;};

class EconomyManager{
  constructor({send,rng=Math.random}){this.send=send;this.rng=rng;}
  act(player,m={}){if(player.trade||player.shop)return this.fail(player,'Feche a troca ou loja pessoal primeiro.');if(m.action==='buy')return this.buy(player,m);if(m.action==='sellEquipment')return this.sellEquipment(player,m);if(m.action==='sellMaterials')return this.sellMaterials(player);if(m.action==='enhance')return this.enhance(player,m);return this.fail(player,'Ação econômica inválida.');}
  buy(player,m){const price=priceOf(m.itemId),known=price&&(CONSUMABLES[m.itemId]||EQUIPMENT[m.itemId]);if(!known)return this.fail(player,'Item inválido.');const d=player.dados,inv=d.inv||(d.inv=[]);if((d.gold||0)<price)return this.fail(player,'Ouro insuficiente.');const stack=CONSUMABLES[m.itemId]&&inv.find(x=>x.id===m.itemId&&x.up===undefined);if(!stack&&inv.length>=24)return this.fail(player,'Mochila cheia.');d.gold-=price;if(stack)stack.n++;else inv.push({id:m.itemId,n:1});return this.done(player,`Comprou ${m.itemId}.`);}
  sellEquipment(player,m){const inv=player.dados.inv||[],i=Number(m.index),entry=inv[i],item=entry&&EQUIPMENT[entry.id];if(!item)return this.fail(player,'Equipamento inválido.');const value=Math.floor(priceOf(entry.id)*.25*(1+.25*(entry.up||0)));inv.splice(i,1);player.dados.gold=(player.dados.gold||0)+value;return this.done(player,`Equipamento vendido por ${value} ouro.`);}
  sellMaterials(player){const inv=player.dados.inv||[],reserved=reservedQuestItems(player);let total=0;for(let i=inv.length-1;i>=0;i--){const value=MATERIAL_VALUES[inv[i].id];if(value&&!reserved.has(inv[i].id)){total+=value*inv[i].n;inv.splice(i,1);}}player.dados.gold=(player.dados.gold||0)+total;return this.done(player,`Materiais vendidos por ${total} ouro.`);}
  enhance(player,m){const d=player.dados,inv=d.inv||[],kind=m.kind,ref=m.ref;let entry,slot;if(kind==='inventory')entry=inv[Number(ref)];else{slot=String(ref);const id=d.eq&&d.eq[slot];if(id)entry={id,up:(d.equp&&d.equp[slot])||0};}if(!entry||!EQUIPMENT[entry.id]||EQUIPMENT[entry.id].slot==='voo')return this.fail(player,'Item inválido.');const current=entry.up||0,next=current+1;if(next>10)return this.fail(player,'Item no nível máximo.');const stones=Math.ceil(next/2),rune=next<=5?'runa_menor':'runa_maior',gold=40*next*next+60;if(count(inv,'pedra_aprimorar')<stones||count(inv,rune)<1||(d.gold||0)<gold)return this.fail(player,'Materiais ou ouro insuficientes.');const protection=!!m.protection&&count(inv,'perg_protecao')>0,luck=!!m.luck&&count(inv,'perg_sorte')>0;remove(inv,'pedra_aprimorar',stones);remove(inv,rune,1);if(protection)remove(inv,'perg_protecao',1);if(luck)remove(inv,'perg_sorte',1);d.gold-=gold;const chance=Math.min(1,UP_CHANCE[next]+(d.upPity||0)*.03+(luck?.1:0));let result='failed';if(this.rng()<chance){if(kind==='inventory')entry.up=next;else d.equp[slot]=next;d.upPity=0;result='success';}else{d.upPity=(d.upPity||0)+1;if(next>=4&&!protection){if(kind==='inventory')inv.splice(inv.indexOf(entry),1);else{d.eq[slot]=null;d.equp[slot]=0;}result='broken';}}return this.done(player,result,{result,level:next});}
  done(player,msg,extra={}){player.dirty=true;this.send(player.ws,{t:'economyState',ok:true,msg,dados:{inv:player.dados.inv,gold:player.dados.gold,eq:player.dados.eq,equp:player.dados.equp,upPity:player.dados.upPity},...extra});return true;}
  fail(player,msg){this.send(player.ws,{t:'economyState',ok:false,msg});return false;}
}
module.exports=EconomyManager;
