'use strict';
const {RECIPES,ITEMS,PROFESSIONS,TOOLS,STATIONS,xpNeed,rollQuality,qualityExtra,repairCostPerPoint}=require('../data/lifestyle');
const EQUIPMENT=require('../data/equipment');const {RARITIES}=require('../data/items/rarities');const {INVENTORY_LIMIT}=require('../items/item-manager');
function levelFromXp(xp){let level=1,left=Math.max(0,Math.floor(Number(xp)||0));while(level<50&&left>=xpNeed(level)){left-=xpNeed(level++);}return level;}
const count=(inv,id)=>inv.filter(x=>x&&x.id===id).reduce((s,x)=>s+Math.max(0,Math.floor(x.n||0)),0);
const remove=(inv,id,n)=>{for(let i=inv.length-1;i>=0&&n>0;i--){const x=inv[i];if(!x||x.id!==id||EQUIPMENT[id])continue;const q=Math.min(n,x.n);x.n-=q;n-=q;if(x.n<=0)inv.splice(i,1);}return n===0;};
class CraftManager{
 constructor({send,itemManager,rng=Math.random}){this.send=send;this.itemManager=itemManager;this.rng=rng;}
 ensure(p){const d=this.itemManager.ensurePlayer(p);d.lifestyle=d.lifestyle&&typeof d.lifestyle==='object'?d.lifestyle:{professions:{},tools:{}};d.lifestyle.professions=d.lifestyle.professions||{};for(const id of Object.keys(PROFESSIONS)){const xp=Math.max(0,Math.floor(Number(d.lifestyle.professions[id]?.xp)||0));d.lifestyle.professions[id]={xp,level:levelFromXp(xp)};}d.lifestyle.tools=d.lifestyle.tools||{};return d;}
 catalog(){return {recipes:RECIPES,materials:ITEMS,stations:STATIONS,tools:TOOLS};}
 near(p,station){const s=STATIONS[station];return s&&Math.hypot(Number(p.x)-s.x,Number(p.z)-s.z)<=s.radius;}
 craft(p,id){const r=RECIPES[String(id||'')];if(!r)return this.fail(p,'Receita inválida.');const d=this.ensure(p),prof=d.lifestyle.professions[r.profession],station=PROFESSIONS[r.profession]?.station;if(!this.near(p,station))return this.fail(p,'Aproxime-se da estação de criação.');if(prof.level<r.level)return this.fail(p,'Nível de profissão insuficiente.');if((d.gold||0)<r.fee)return this.fail(p,'Ouro insuficiente.');for(const x of r.inputs)if(count(d.inv,x.id)<x.n)return this.fail(p,'Materiais insuficientes.');const outId=r.output.id;if(outId&&!d.inv.some(x=>x&&x.id===outId)&&d.inv.length>=INVENTORY_LIMIT)return this.fail(p,'Mochila cheia.');for(const x of r.inputs)remove(d.inv,x.id,x.n);d.gold-=r.fee;const quality=rollQuality(prof.level-r.level,this.rng);if(r.output.tool){d.lifestyle.tools[TOOLS[r.output.tool].line]=r.output.tool;}else{const qty=r.output.n+qualityExtra(r.output.n,quality);if(!this.itemManager.addItem(p,{id:outId,n:qty}))return this.fail(p,'Falha ao criar item.');}prof.xp+=r.xp;prof.level=levelFromXp(prof.xp);p.dirty=true;this.itemManager.sync(p,{event:'craft'});this.send(p.ws,{t:'craftResult',ok:true,recipeId:id,quality,fee:r.fee,lifestyle:d.lifestyle});return true;}
 repair(p,slot){const d=this.ensure(p),s=String(slot||''),id=d.eq?.[s],item=EQUIPMENT[id];if(!item)return this.fail(p,'Equipamento inválido.');if(!this.near(p,'forja'))return this.fail(p,'Aproxime-se da forja para reparar.');d.eqMeta[s]=d.eqMeta[s]||{};const cur=Math.max(0,Math.min(100,Number(d.eqMeta[s].durability??100)));if(cur>=100)return this.fail(p,'Equipamento não precisa de reparo.');const rarity=RARITIES[d.eqMeta[s].rarity||item.rarity]||{},cost=Math.max(1,Math.ceil((100-cur)*repairCostPerPoint(item,rarity)));if((d.gold||0)<cost)return this.fail(p,'Ouro insuficiente.');d.gold-=cost;d.eqMeta[s].durability=100;p.dirty=true;this.itemManager.sync(p,{event:'repair'});this.send(p.ws,{t:'repairResult',ok:true,slot:s,cost});return true;}
 fail(p,msg){this.send(p.ws,{t:'craftResult',ok:false,msg});return false;}
}
module.exports=CraftManager;
