'use strict';
const {NODES,PROFESSIONS,TOOLS,xpNeed,BYPRODUCTS}=require('../data/lifestyle');
const {INVENTORY_LIMIT}=require('../items/item-manager');
const STARTER={mineracao:'picareta_bronze',lenhador:'machado_lenha_bronze',herbalismo:'foice_bronze',pesca:'vara_bronze'};
function levelFromXp(xp){let level=1,left=Math.max(0,Math.floor(Number(xp)||0));while(level<50&&left>=xpNeed(level)){left-=xpNeed(level++);}return level;}
class GatherManager{
 constructor({send,itemManager,now=()=>Date.now(),rng=Math.random}){this.send=send;this.itemManager=itemManager;this.now=now;this.rng=rng;this.nodes=new Map(NODES.map(n=>[n.id,{...n,readyAt:0,charges:n.charges,claimed:false}]));}
 ensure(p){const d=p.dados||(p.dados={}),src=d.lifestyle&&typeof d.lifestyle==='object'?d.lifestyle:{};const professions={};for(const id of Object.keys(PROFESSIONS)){const xp=Math.max(0,Math.floor(Number(src.professions?.[id]?.xp)||0));professions[id]={xp,level:levelFromXp(xp)};}const tools={...(src.tools||{})};for(const [line,id] of Object.entries(STARTER))if(!TOOLS[tools[line]])tools[line]=id;d.lifestyle={...src,professions,tools};return d.lifestyle;}
 catalog(){return {nodes:NODES.map(n=>({...n})),professions:Object.values(PROFESSIONS).map(x=>({...x})),tools:Object.values(TOOLS).map(x=>({...x}))};}
 snapshot(){const now=this.now();return [...this.nodes.values()].map(n=>({id:n.id,ready:!n.claimed&&(n.readyAt<=now),readyAt:n.readyAt,charges:n.readyAt<=now?(n.charges||n.charges===0?n.charges:n.charges):0}));}
 sync(p,extra={}){this.send(p.ws,{t:'lifestyleState',state:this.ensure(p),nodes:this.snapshot(),...extra});}
 gather(p,nodeId){const n=this.nodes.get(String(nodeId||'')),now=this.now();if(!n)return this.fail(p,'Recurso inválido.');if(n.readyAt&&n.readyAt<=now&&n.charges<=0){n.charges=n.charges||NODES.find(x=>x.id===n.id).charges;n.readyAt=0;}if(n.claimed||n.readyAt>now||n.charges<=0)return this.fail(p,'Este recurso ainda está se regenerando.');if(Math.hypot(Number(p.x)-n.x,Number(p.z)-n.z)>n.range+1)return this.fail(p,'Aproxime-se do recurso.');const state=this.ensure(p),prof=state.professions[n.line];if(prof.level<n.level)return this.fail(p,'Nível de profissão insuficiente.');const tool=TOOLS[state.tools[n.line]];if(!tool||tool.line!==n.line||tool.tier<n.toolTier)return this.fail(p,'Ferramenta insuficiente.');const d=this.itemManager.ensurePlayer(p),existing=d.inv.find(x=>x&&x.id===n.item);if(!existing&&d.inv.length>=INVENTORY_LIMIT)return this.fail(p,'Mochila cheia.');n.claimed=true;const qty=n.yield[0]+Math.floor(this.rng()*(n.yield[1]-n.yield[0]+1));if(!this.itemManager.addItem(p,{id:n.item,n:qty})){n.claimed=false;return this.fail(p,'Mochila cheia.');}for(const b of BYPRODUCTS[n.line]||[])if(n.tier>=b.minTier&&this.rng()<b.chance)this.itemManager.addItem(p,{id:b.id,n:1});prof.xp+=n.xp;prof.level=levelFromXp(prof.xp);n.charges--;if(n.charges<=0)n.readyAt=now+n.respawnMs;n.claimed=false;p.dirty=true;this.itemManager.sync(p,{event:'gather'});this.sync(p,{event:'gather',nodeId:n.id,reward:{id:n.item,n:qty},profession:n.line});return true;}
 fail(p,msg){this.send(p.ws,{t:'lifestyleState',ok:false,msg,state:this.ensure(p),nodes:this.snapshot()});return false;}
}
module.exports=GatherManager;
