'use strict';const {randomUUID}=require('node:crypto');
class SocialManager{
 constructor({players,send,itemManager,save,lookupByName=null}){this.players=players;this.send=send;this.itemManager=itemManager;this.save=save;this.lookupByName=lookupByName;this.mail=new Map();}
 ensure(p){const d=p.dados||(p.dados={});d.social=d.social&&typeof d.social==='object'?d.social:{friends:[],blacklist:[],lastSeen:{}};d.social.friends=Array.isArray(d.social.friends)?d.social.friends:[];d.social.blacklist=Array.isArray(d.social.blacklist)?d.social.blacklist:[];d.social.lastSeen=d.social.lastSeen||{};d.mail=Array.isArray(d.mail)?d.mail:[];return d;}
 byName(name){const n=String(name||'').trim().toLowerCase();return [...this.players.values()].find(p=>p.name.toLowerCase()===n)||null;}
 snapshot(p){const d=this.ensure(p),online=new Map([...this.players.values()].map(x=>[x.name.toLowerCase(),x]));return {friends:d.social.friends.map(name=>{const o=online.get(name.toLowerCase());return {name,online:!!o,lastActivity:o?Date.now():(d.social.lastSeen[name]||null),level:o?o.L:null,cls:o?.dados?.cls||null};}),blacklist:[...d.social.blacklist],mail:d.mail.map(x=>({...x,items:(x.items||[]).map(i=>({...i}))}))};}
 sync(p,extra={}){this.send(p.ws,{t:'socialState',state:this.snapshot(p),...extra});}
 addFriend(p,name){const d=this.ensure(p),o=this.byName(name);if(!o||o===p)return false;if(d.social.blacklist.includes(o.name))return false;if(!d.social.friends.includes(o.name))d.social.friends.push(o.name);const od=this.ensure(o);if(!od.social.friends.includes(p.name))od.social.friends.push(p.name);p.dirty=o.dirty=true;this.sync(p,{event:'friend'});this.sync(o,{event:'friend'});return true;}
 removeFriend(p,name){const d=this.ensure(p);d.social.friends=d.social.friends.filter(x=>x!==name);p.dirty=true;this.sync(p,{event:'friend-remove'});return true;}
 block(p,name){const d=this.ensure(p);name=String(name||'').trim();if(!name||name===p.name)return false;if(!d.social.blacklist.includes(name))d.social.blacklist.push(name);d.social.friends=d.social.friends.filter(x=>x!==name);p.dirty=true;this.sync(p,{event:'block'});return true;}
 unblock(p,name){const d=this.ensure(p);d.social.blacklist=d.social.blacklist.filter(x=>x!==name);p.dirty=true;this.sync(p,{event:'unblock'});return true;}
 whisper(p,name,msg){const o=this.byName(name),text=String(msg||'').trim().slice(0,300);if(!o||!text)return false;const a=this.ensure(p),b=this.ensure(o);if(a.social.blacklist.includes(o.name)||b.social.blacklist.includes(p.name))return false;this.send(o.ws,{t:'whisper',from:p.name,msg:text,at:Date.now()});this.send(p.ws,{t:'whisper',from:p.name,to:o.name,msg:text,at:Date.now()});return true;}
 sendMail(p,name,subject,body,items=[],gold=0){const o=this.byName(name);if(!o)return {ok:false,reason:'Destinatário precisa estar online nesta versão.'};subject=String(subject||'').trim().slice(0,60);body=String(body||'').trim().slice(0,600);gold=Math.max(0,Math.min(1e9,Math.floor(Number(gold)||0)));if(!subject)return {ok:false,reason:'Assunto obrigatório.'};const src=this.ensure(p),dst=this.ensure(o);if((src.gold||0)<gold)return {ok:false,reason:'Ouro insuficiente.'};const normalized=[];for(const it of Array.isArray(items)?items.slice(0,8):[]){const row=src.inv?.find(x=>x&&x.id===it.id&&(it.uid?x.uid===it.uid:true)&&!x.locked);if(!row)return {ok:false,reason:'Item indisponível.'};normalized.push({...row,n:Math.max(1,Math.min(row.n||1,Math.floor(it.n||1)))});}
 const backup=JSON.parse(JSON.stringify(src.inv||[])),backupGold=src.gold||0;try{for(const it of normalized){const row=src.inv.find(x=>x.id===it.id&&(it.uid?x.uid===it.uid:true));if(row.n>it.n)row.n-=it.n;else src.inv.splice(src.inv.indexOf(row),1);}src.gold=backupGold-gold;const mail={id:randomUUID(),from:p.name,to:o.name,subject,body,items:normalized,gold,at:Date.now(),claimed:false};dst.mail.unshift(mail);p.dirty=o.dirty=true;this.sync(o,{event:'mail'});this.itemManager.sync(p,{event:'mail-send'});return {ok:true,id:mail.id};}catch(e){src.inv=backup;src.gold=backupGold;return {ok:false,reason:'Falha transacional.'};}}
 claimMail(p,id){const d=this.ensure(p),m=d.mail.find(x=>x.id===id);if(!m||m.claimed)return {ok:false};const inv=JSON.parse(JSON.stringify(d.inv||[])),gold=d.gold||0;for(const it of m.items||[])if(!this.itemManager.addItem(p,it)){d.inv=inv;d.gold=gold;return {ok:false,reason:'Mochila cheia.'};}d.gold=gold+(m.gold||0);m.claimed=true;m.items=[];m.gold=0;p.dirty=true;this.itemManager.sync(p,{event:'mail-claim'});this.sync(p);return {ok:true};}
 onLogin(p){this.ensure(p);this.sync(p,{event:'login'});for(const o of this.players.values())if(o!==p&&this.ensure(o).social.friends.includes(p.name))this.sync(o,{event:'friend-online'});}
 onDisconnect(p){const now=Date.now();for(const o of this.players.values()){const d=this.ensure(o);if(d.social.friends.includes(p.name)){d.social.lastSeen[p.name]=now;o.dirty=true;this.sync(o,{event:'friend-offline'});}}}
 handle(p,m){if(m.action==='friend')return this.addFriend(p,m.name);if(m.action==='unfriend')return this.removeFriend(p,m.name);if(m.action==='block')return this.block(p,m.name);if(m.action==='unblock')return this.unblock(p,m.name);if(m.action==='whisper')return this.whisper(p,m.name,m.msg);if(m.action==='mailSend')return this.sendMail(p,m.name,m.subject,m.body,m.items,m.gold);if(m.action==='mailClaim')return this.claimMail(p,m.id);if(m.action==='sync'){this.sync(p);return true;}return false;}
}
module.exports=SocialManager;