'use strict';
const {randomUUID}=require('node:crypto');
class DungeonManager{
 constructor({catalog,players,send,now=Date.now,idFactory=randomUUID}){this.catalog=catalog;this.players=players;this.send=send;this.now=now;this.idFactory=idFactory;this.instances=new Map();this.playerInstance=new Map();this.lockouts=new Map();this.analytics=[];this.completionCounts=new Map();}
 config(id){const c=this.catalog[id];if(!c)throw new Error('Dungeon desconhecida: '+id);return c;}
 validateEntry(player,dungeonId,difficulty='normal'){const c=this.config(dungeonId),party=player.party,members=party?[...party.members].map(id=>this.players.get(id)).filter(Boolean):[player];if(party&&party.leader!==player.id)return {ok:false,reason:'Apenas o líder pode iniciar a dungeon.'};if(members.length<c.partyMin||members.length>c.partyMax)return {ok:false,reason:'Grupo deve ter '+c.partyMin+'-'+c.partyMax+' jogadores.'};if(members.some(p=>p.L<c.levelMin||p.L>c.levelMax))return {ok:false,reason:'Nível exigido: '+c.levelMin+'-'+c.levelMax+'.'};const diff=c.difficulties[difficulty];if(!diff)return {ok:false,reason:'Dificuldade inválida.'};if(diff.unlockCompletions&&members.some(p=>this.completions(p.id,dungeonId)<diff.unlockCompletions))return {ok:false,reason:'Dificuldade ainda não desbloqueada.'};const now=this.now();if(members.some(p=>(this.lockouts.get(p.id+':'+dungeonId)||0)>now))return {ok:false,reason:'Um membro está em lockout.'};if(members.some(p=>this.playerInstance.has(p.id)))return {ok:false,reason:'Um membro já está em uma instância.'};return {ok:true,c,members,diff};}
 create(player,dungeonId,difficulty='normal'){const v=this.validateEntry(player,dungeonId,difficulty);if(!v.ok)return v;const id=this.idFactory(),now=this.now(),inst={id,dungeonId,difficulty,participants:new Set(v.members.map(p=>p.id)),connected:new Set(v.members.map(p=>p.id)),state:'active',stageIndex:0,stageProgress:0,wavesCleared:0,wipes:0,startedAt:now,expiresAt:now+v.c.timeoutMs,completedAt:0,chestClaimed:new Set(),events:[]};this.instances.set(id,inst);this.spawnStage(inst);for(const p of v.members){this.playerInstance.set(p.id,id);p.dungeonInstanceId=id;this.send(p.ws,{t:'dungeonEnter',instance:this.public(inst),config:this.publicConfig(v.c),entities:this.publicEntities(inst)});}this.event(inst,'start',{partySize:v.members.length});return {ok:true,instance:inst};}
 publicConfig(c){return {id:c.id,name:c.name,levelMin:c.levelMin,levelMax:c.levelMax,stages:c.stages,bosses:c.bosses,difficulties:c.difficulties};}
 publicEntities(i){return [...(i.entities||new Map()).values()].map(e=>({...e}));}
 spawnStage(i){const c=this.config(i.dungeonId),s=c.stages[i.stageIndex],diff=c.difficulties[i.difficulty],entities=new Map();if(!s){i.entities=entities;return;}if(s.type==='wave'){const w=s.waves[Math.min(i.wavesCleared,s.waves.length-1)];for(let n=0;n<w.count;n++){const id='mob-'+i.stageIndex+'-'+i.wavesCleared+'-'+n;entities.set(id,{id,kind:'mob',name:'Sentinela do Eco',hp:Math.round(650*diff.hp),maxHp:Math.round(650*diff.hp),level:24});}}else if(s.type==='miniboss'||s.type==='boss'){const b=c.bosses[s.boss];entities.set(s.boss,{id:s.boss,kind:s.type,name:b.name,hp:Math.round(b.hp*diff.hp),maxHp:Math.round(b.hp*diff.hp),level:b.level,mechanics:b.mechanics});}i.entities=entities;this.broadcast(i,{t:'dungeonEntities',entities:this.publicEntities(i)});}
 attack(player,targetId){const i=this.getForPlayer(player.id);if(!i||i.state!=='active'||!i.participants.has(player.id))return {ok:false};const e=i.entities&&i.entities.get(targetId);if(!e||e.hp<=0)return {ok:false};const atk=Math.max(20,Math.round((player.stats&&player.stats.attack)||player.L*5));const damage=Math.max(1,Math.round(atk*(.85+Math.random()*.3)));e.hp=Math.max(0,e.hp-damage);this.broadcast(i,{t:'dungeonHit',targetId:e.id,damage,hp:e.hp,maxHp:e.maxHp});if(e.kind==='miniboss'||e.kind==='boss'){const mech=e.mechanics[Math.floor(Math.random()*e.mechanics.length)];if(Math.random()<.28)this.bossMechanic(i.id,mech,{x:0,z:0});}if(e.hp===0){i.entities.delete(e.id);if(i.entities.size===0){const s=this.config(i.dungeonId).stages[i.stageIndex];if(s.type==='wave'){i.wavesCleared++;if(i.wavesCleared>=s.waves.length)this.advanceStage(i,s);else this.spawnStage(i);}else this.advanceStage(i,s);}}return {ok:true,damage};}
 advanceStage(i,s){this.event(i,'stageComplete',{stage:s.id});i.stageIndex++;i.stageProgress=0;i.wavesCleared=0;this.broadcast(i,{t:'dungeonStage',instance:this.public(i),gate:s.gate||null});if(i.stageIndex>=this.config(i.dungeonId).stages.length)this.complete(i);else this.spawnStage(i);}

 public(i){return {id:i.id,dungeonId:i.dungeonId,difficulty:i.difficulty,state:i.state,stageIndex:i.stageIndex,stageProgress:i.stageProgress,wipes:i.wipes,startedAt:i.startedAt,expiresAt:i.expiresAt,participants:[...i.participants]};}
 event(i,type,data={}){const e={at:this.now(),instanceId:i.id,dungeonId:i.dungeonId,type,...data};i.events.push(e);this.analytics.push(e);return e;}
 getForPlayer(id){const iid=this.playerInstance.get(id);return iid?this.instances.get(iid)||null:null;}
 disconnect(player){const i=this.getForPlayer(player.id);if(i){i.connected.delete(player.id);this.event(i,'disconnect',{playerId:player.id});}}
 reconnect(player){const i=this.getForPlayer(player.id);if(!i||i.state!=='active'||this.now()>=i.expiresAt)return null;i.connected.add(player.id);player.dungeonInstanceId=i.id;this.send(player.ws,{t:'dungeonReconnect',instance:this.public(i),config:this.publicConfig(this.config(i.dungeonId)),entities:this.publicEntities(i)});this.event(i,'reconnect',{playerId:player.id});return i;}
 progress(player,kind,target,count=1){const i=this.getForPlayer(player.id);if(!i||i.state!=='active')return {ok:false};const c=this.config(i.dungeonId),s=c.stages[i.stageIndex];if(!s)return {ok:false};let done=false;if(s.type==='wave'&&kind==='wave'){i.wavesCleared+=count;i.stageProgress=i.wavesCleared;done=i.wavesCleared>=s.waves.length;}else if(s.type==='objective'&&kind===s.objective.type&&target===s.objective.target){i.stageProgress+=count;done=i.stageProgress>=s.objective.count;}else if((s.type==='miniboss'||s.type==='boss')&&kind==='boss'&&target===s.boss){done=true;i.stageProgress=1;}if(done){this.event(i,'stageComplete',{stage:s.id});i.stageIndex++;i.stageProgress=0;i.wavesCleared=0;this.broadcast(i,{t:'dungeonStage',instance:this.public(i),gate:s.gate||null});if(i.stageIndex>=c.stages.length)this.complete(i);}return {ok:true,done,instance:i};}
 bossMechanic(iid,mechanic,target={x:0,z:0}){const i=this.instances.get(iid),c=i&&this.config(i.dungeonId);if(!i||i.state!=='active')return null;const s=c.stages[i.stageIndex],boss=c.bosses[s&&s.boss];if(!boss||!boss.mechanics.includes(mechanic))return null;const evt={t:'dungeonTelegraph',instanceId:i.id,mechanic,x:target.x,z:target.z,radius:mechanic==='circulo'||mechanic==='soak'?5:3,executeAt:this.now()+1200};this.broadcast(i,evt);this.event(i,'mechanic',{mechanic});return evt;}
 wipe(iid){const i=this.instances.get(iid);if(!i||i.state!=='active')return false;i.wipes++;this.event(i,'wipe',{wipes:i.wipes});this.broadcast(i,{t:'dungeonWipe',wipes:i.wipes});return true;}
 complete(i){if(i.state!=='active')return;i.state='completed';i.completedAt=this.now();const c=this.config(i.dungeonId);for(const id of i.participants){this.lockouts.set(id+':'+i.dungeonId,this.now()+c.lockoutMs);this.completionCounts.set(id+':'+i.dungeonId,(this.completionCounts.get(id+':'+i.dungeonId)||0)+1);const p=this.players.get(id);if(p)this.send(p.ws,{t:'dungeonComplete',instance:this.public(i),chest:true,loot:c.loot[i.difficulty]});}this.event(i,'complete',{durationMs:i.completedAt-i.startedAt,wipes:i.wipes,difficulty:i.difficulty});}
 claimChest(player){const i=this.getForPlayer(player.id);if(!i||i.state!=='completed'||i.chestClaimed.has(player.id))return {ok:false};i.chestClaimed.add(player.id);const loot=this.config(i.dungeonId).loot[i.difficulty];this.event(i,'chest',{playerId:player.id});return {ok:true,loot};}
 completions(playerId,dungeonId){return this.completionCounts.get(playerId+':'+dungeonId)||0;}
 broadcast(i,msg){for(const id of i.participants){const p=this.players.get(id);if(p&&p.ws)this.send(p.ws,msg);}}
 tick(){const now=this.now();for(const i of [...this.instances.values()])if(i.state==='active'&&now>=i.expiresAt){i.state='expired';this.event(i,'timeout');this.broadcast(i,{t:'dungeonExpired',instanceId:i.id});this.cleanup(i);}}
 cleanup(i){for(const id of i.participants){if(this.playerInstance.get(id)===i.id)this.playerInstance.delete(id);const p=this.players.get(id);if(p&&p.dungeonInstanceId===i.id)delete p.dungeonInstanceId;}if(i.state!=='active')this.instances.delete(i.id);}
}
module.exports=DungeonManager;
