'use strict';const {ARENAS,TERRITORIES,HONOR}=require('../data/pvp');
class PvpManager{
constructor({players,send,skillManager=null,now=Date.now}){Object.assign(this,{players,send,skillManager,now});this.duels=new Map;this.queue=[];this.wars=new Map;this.territories=new Map(Object.keys(TERRITORIES).map(k=>[k,null]));}
ensure(p){const d=p.dados||(p.dados={}),z=d.pvp=d.pvp||{};for(const k of ['honor','kills','deaths','duelWins','duelLosses','arenaWins','arenaLosses','guildKills','streak','bestStreak'])z[k]=Math.max(0,Math.floor(+z[k]||0));return z;}
byName(n){n=String(n||'').trim().toLowerCase();return[...this.players.values()].find(x=>x.name.toLowerCase()===n)||null} key(a,b){return[a.id,b.id].sort((x,y)=>x-y).join(':')}
duel(a,b){const d=this.duels.get(this.key(a,b));return d&&d.accepted&&d.until>this.now()?d:null} war(a,b){if(!a.guild||!b.guild||a.guild.id===b.guild.id)return null;return this.wars.get([a.guild.id,b.guild.id].sort().join(':'))||null}
fail(p,reason){this.send(p.ws,{t:'pvpState',ok:false,reason,state:this.snapshot(p)});return false} sync(p,extra={}){this.send(p.ws,{t:'pvpState',state:this.snapshot(p),...extra})}
invite(p,name){const o=this.byName(name);if(!o||o===p||p.dead||o.dead)return this.fail(p,'Jogador indisponível.');if(Math.hypot(p.x-o.x,p.z-o.z)>18)return this.fail(p,'Adversário distante.');this.duels.set(this.key(p,o),{a:p.id,b:o.id,inviter:p.id,accepted:false,until:this.now()+30000});this.send(o.ws,{t:'pvpInvite',kind:'duel',from:p.name});return true}
accept(p,name){const o=this.byName(name),d=o&&this.duels.get(this.key(p,o));if(!d||d.accepted||d.inviter===p.id||d.until<=this.now())return this.fail(p,'Convite expirado.');d.accepted=true;d.until=this.now()+180000;for(const x of [p,o])this.send(x.ws,{t:'pvpEvent',event:'duel-start',opponent:x===p?o.name:p.name});return true}
declare(p,name){if(!p.guild||p.guild.cargo!=='lider')return this.fail(p,'Somente o líder declara guerra.');const o=this.byName(name);if(!o?.guild||o.guild.id===p.guild.id)return this.fail(p,'Guilda adversária inválida.');const k=[p.guild.id,o.guild.id].sort().join(':');if(this.wars.has(k))return this.fail(p,'Guerra já registrada.');const w={a:p.guild.id,b:o.guild.id,names:[p.guild.nome,o.guild.nome],accepted:false,score:{[p.guild.id]:0,[o.guild.id]:0},until:this.now()+60000};this.wars.set(k,w);for(const x of this.players.values())if(x.guild?.id===o.guild.id&&x.guild.cargo==='lider')this.send(x.ws,{t:'pvpInvite',kind:'guild-war',from:p.guild.nome,player:p.name});return true}
acceptWar(p,name){if(!p.guild||p.guild.cargo!=='lider')return this.fail(p,'Somente o líder aceita guerra.');const o=[...this.players.values()].find(x=>x.guild?.nome===name&&x.guild.id!==p.guild.id),w=o&&this.war(p,o);if(!w||w.accepted||w.until<=this.now())return this.fail(p,'Declaração expirada.');w.accepted=true;w.until=this.now()+1800000;this.broadcastWar(w,'guild-war-start');return true}
broadcastWar(w,event){for(const x of this.players.values())if(x.guild&&(x.guild.id===w.a||x.guild.id===w.b))this.send(x.ws,{t:'pvpEvent',event,war:{names:w.names,score:w.score,until:w.until}})}
canAttack(a,b){if(!a||!b||a===b||a.dead||b.dead)return false;if(this.duel(a,b))return true;const w=this.war(a,b);return!!(w?.accepted&&w.until>this.now()||a.pvpArena&&a.pvpArena===b.pvpArena)}
attack(p,name,skillId){const o=this.byName(name);if(!this.canAttack(p,o))return this.fail(p,'PvP não autorizado.');let mult=1,range=3.2;if(skillId){const s=this.skillManager?.resolved(p,skillId);if(!s||['heal','party-heal','buff','passive'].includes(s.type))return this.fail(p,'Habilidade PvP inválida.');mult=Math.max(.4,Math.min(2.2,+s.multiplier||1));range=Math.max(3.2,+s.range||3.2)}if(Math.hypot(p.x-o.x,p.z-o.z)>range)return this.fail(p,'Alvo distante.');const atk=Math.max(1,+p.stats?.atkMax||20),def=Math.max(0,+o.stats?.defense||0),damage=Math.max(1,Math.round(atk*mult*.72-def*.28));o.hp=Math.max(0,o.hp-damage);o.dados.hp=o.hp;o.dirty=true;this.send(o.ws,{t:'pvpHit',from:p.name,damage,hp:o.hp,maxHp:o.stats?.maxHp||o.maxHp});this.send(p.ws,{t:'pvpHit',to:o.name,damage,hp:o.hp,maxHp:o.stats?.maxHp||o.maxHp});if(!o.hp)this.kill(p,o);return true}
kill(k,v){v.dead=true;const a=this.ensure(k),b=this.ensure(v);a.kills++;a.streak++;a.bestStreak=Math.max(a.bestStreak,a.streak);b.deaths++;b.streak=0;let gain=HONOR.duelWin,w=this.war(k,v),d=this.duel(k,v);if(k.pvpArena&&k.pvpArena===v.pvpArena){gain=HONOR.arenaWin;a.arenaWins++;b.arenaLosses++;this.leaveArena(k);this.leaveArena(v)}else if(w?.accepted){gain=HONOR.guildKill;a.guildKills++;w.score[k.guild.id]=(w.score[k.guild.id]||0)+1;this.broadcastWar(w,'guild-war-score')}else if(d){a.duelWins++;b.duelLosses++;this.duels.delete(this.key(k,v))}a.honor+=gain;b.honor=Math.max(0,b.honor-HONOR.deathLoss);k.dirty=v.dirty=true;this.send(v.ws,{t:'playerDeath',pvp:true,killer:k.name});this.sync(k,{event:'victory'});this.sync(v,{event:'defeat'})}
queueArena(p){const a=ARENAS.campo_honra;if(p.L<a.minLevel)return this.fail(p,'Arena libera no nível '+a.minLevel+'.');if(p.dead||p.pvpArena)return this.fail(p,'Fila indisponível.');if(!this.queue.includes(p.id))this.queue.push(p.id);this.match();this.sync(p,{event:'arena-queue'});return true}
match(){while(this.queue.length>=2){const a=this.players.get(this.queue.shift()),b=this.players.get(this.queue.shift());if(!a||!b||a.dead||b.dead)continue;const r=ARENAS.campo_honra;a.pvpArena=b.pvpArena=r.id;Object.assign(a,{x:r.center.x-5,z:r.center.z,posDirty:true});Object.assign(b,{x:r.center.x+5,z:r.center.z,posDirty:true});this.send(a.ws,{t:'pvpEvent',event:'arena-start',opponent:b.name,arena:r});this.send(b.ws,{t:'pvpEvent',event:'arena-start',opponent:a.name,arena:r})}}
leaveArena(p){this.queue=this.queue.filter(id=>id!==p.id);p.pvpArena=null}
capture(p,id){const t=TERRITORIES[id];if(!t||!p.guild)return this.fail(p,'Território inválido.');if((p.guild.nivel||1)<t.minGuildLevel)return this.fail(p,'Nível de guilda insuficiente.');if(Math.hypot(p.x-t.x,p.z-t.z)>t.radius)return this.fail(p,'Entre na área do objetivo.');if(this.territories.get(id)?.guildId===p.guild.id)return this.fail(p,'Território já controlado.');this.territories.set(id,{guildId:p.guild.id,name:p.guild.nome,at:this.now()});this.ensure(p).honor+=HONOR.territoryCapture;p.dirty=true;for(const x of this.players.values())this.send(x.ws,{t:'pvpEvent',event:'territory-captured',territory:t.name,guild:p.guild.nome,player:p.name});this.sync(p);return true}
ranking(){return[...this.players.values()].map(p=>({name:p.name,L:p.L,guild:p.guild?.nome||null,...this.ensure(p)})).sort((a,b)=>b.honor-a.honor||b.kills-a.kills).slice(0,50)}
snapshot(p){return{self:{...this.ensure(p)},queue:this.queue.includes(p.id),arena:p.pvpArena||null,ranking:this.ranking(),territories:Object.entries(TERRITORIES).map(([id,t])=>({...t,owner:this.territories.get(id)})),wars:[...this.wars.values()].filter(w=>p.guild&&(w.a===p.guild.id||w.b===p.guild.id))}}
handle(p,m){if(m.action==='sync'){this.sync(p);return true}if(m.action==='duel')return this.invite(p,m.name);if(m.action==='duelAccept')return this.accept(p,m.name);if(m.action==='attack')return this.attack(p,m.name,m.skillId);if(m.action==='arenaQueue')return this.queueArena(p);if(m.action==='arenaLeave'){this.leaveArena(p);this.sync(p);return true}if(m.action==='warDeclare')return this.declare(p,m.name);if(m.action==='warAccept')return this.acceptWar(p,m.name);if(m.action==='capture')return this.capture(p,m.id);return this.fail(p,'Ação PvP inválida.')}
onLogin(p){this.ensure(p);this.sync(p,{event:'login'})}onDisconnect(p){this.leaveArena(p);for(const[k,x]of this.duels)if(x.a===p.id||x.b===p.id)this.duels.delete(k)}tick(){const n=this.now();for(const[k,x]of this.duels)if(x.until<=n)this.duels.delete(k);for(const[k,w]of this.wars)if(w.until<=n){this.broadcastWar(w,'guild-war-end');this.wars.delete(k)}}}
module.exports=PvpManager;